export enum CuisineEnum {
  Dessert = 'dessert',
  Chinese = 'chinese',
  Fried = 'fried',
  Asian = 'asian',
  Burgers = 'burgers',
  Mexican = 'mexican',
  Italian = 'italian',
  Indian = 'indian',
  Thai = 'thai',
  American = 'american',
  MiddleEastern = 'middle-eastern',
  BBQ = 'bbq',
  Vegan = 'vegan',
  Vegetarian = 'vegetarian',
  Seafood = 'seafood',
  Pizza = 'pizza',
  Sandwiches = 'sandwiches',
}
