export enum CuisineEnum {
  Dessert = 'Dessert',
  Chinese = 'Chinese',
  Fried = 'Fried',
  Asian = 'Asian',
  Burgers = 'Burgers',
  Mexican = 'Mexican',
  Italian = 'Italian',
  Indian = 'Indian',
  Thai = 'Thai',
  American = 'American',
  MiddleEastern = 'Middle-Eastern',
  BBQ = 'BBQ',
  Vegan = 'Vegan',
  Vegetarian = 'Vegetarian',
  Seafood = 'Seafood',
  Pizza = 'Pizza',
  Sandwiches = 'Sandwiches',
}
